oclint_json_file: /Users/kino/Desktop/OCLintTestProj/xxxxxxx/oclint_report.json
projConfig:
  filterMode: ''
  indicDirName: hello
  proj_path: /Users/kino/Desktop/OCLintTestProj/xxxxxxx
  schemeName: xxxxxxx
  useWorkspace: false
